tunnel: 55e399d9-4562-4286-bac1-843e42840c6d
credentials-file: /etc/cloudflared/pupculture.json

ingress:
  - hostname: admin.pupculture.site
    service: http://adminui:80

  - hostname: api.pupculture.site
    service: http://api:3001

  - hostname: ws.pupculture.site
    service: http://ws:3001

  - hostname: nodered.pupculture.site
    service: http://nodered:1880

  - hostname: files.pupculture.site
    service: http://minio:9000

  - service: http_status:404
